In [1]:
import numpy as np


In [6]:
array1 = np.array([1,2,3])
array1

array([1, 2, 3])

In [7]:
array2 = np.array([4,5,6])
array2

array([4, 5, 6])

In [8]:
print(array1 + array2)

[5 7 9]


In [9]:
print(type(array1))

<class 'numpy.ndarray'>


In [11]:
array2.ndim

1

In [22]:
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [32]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
arr2.ndim


[[1 2 3 4]
 [5 6 7 8]]


2

In [30]:
arr2.shape

(2, 4)

In [36]:
arr2.itemsize


8

In [39]:
arr2.size

8

In [38]:
arr2.nbytes

64

In [40]:
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [53]:
arr3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]]])
arr3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [54]:
arr3.shape

(1, 3, 3)

In [44]:
arr3.nbytes

72

In [46]:
arr3.itemsize

8

In [47]:
arr4 = np.array([[[1,2,3],[6,5,2],[9,0,8]]])
arr4

array([[[1, 2, 3],
        [6, 5, 2],
        [9, 0, 8]]])

In [49]:
print(arr3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [50]:
print(arr3*arr4)

[[[ 1  4  9]
  [24 25 12]
  [63  0 72]]]


In [55]:
print(arr4)

[[[1 2 3]
  [6 5 2]
  [9 0 8]]]


In [67]:
arr4 = np.array([[[1,2,3,4,5],[5,7,8,9,10],[11,3,56,25,64]]])
print(arr4)


[[[ 1  2  3  4  5]
  [ 5  7  8  9 10]
  [11  3 56 25 64]]]


In [78]:
arr4[0:2]

array([[[ 1,  2,  3,  4,  5],
        [ 5,  7,  8,  9, 10],
        [11,  3, 56, 25, 64]]])

In [73]:
arr5 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr5)

[ 1  2  3  4  5  6  7  8  9 10]


In [80]:
arr5[1:9]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [85]:
print(arr2[0,0:3])

[1 2 3]


In [87]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [88]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [91]:
np.ones((2,5,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [93]:
for i in arr2:
    for a in i:
        print(a)

1
2
3
4
5
6
7
8
