# Numpy
used to create array , 

In [44]:
import numpy as np

In [45]:
# create array using numpy

a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
print(a)
print(b)
type(a)

[1 2 3 4 5]
[5 4 3 2 1]


numpy.ndarray

In [46]:
#operations
print(a+b)
print(a-b)
print(a*b)

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]


In [47]:
#Creating a 2-D array

a2 = np.array([[1,2,3,],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [48]:
#Creating a 3-D array

a3 = np.array([[[1,2,3],[4,5,6]],            # []-> 1d, [[]]-> 2d, [[[]]]-> 3d
               [[7,8,9],[10,11,12]],
               [[13,14,15],[16,17,18]]])
print(a3)
type(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


numpy.ndarray

In [49]:
print(a2.shape)

(2, 3)


In [50]:
print(a3.shape)   #shape = used to find shape of array

(3, 2, 3)


In [51]:
print(a2.ndim)

2


In [52]:
print(a3.ndim)   #ndim = used to find dimension of array

3


In [53]:
print(a2.dtype)
print(a3.dtype)   #dtype = used to find type of array

int64
int64


In [54]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [57]:
np.random.randint(1,11, size=(2,3))    # 2 - row and 3 - column

array([[1, 3, 1],
       [8, 2, 4]], dtype=int32)

In [58]:
np.random.randint(1,11, size=(3,2,3))

array([[[10,  3,  8],
        [ 9,  4, 10]],

       [[ 6,  9,  8],
        [ 7,  7,  2]],

       [[ 9,  8,  2],
        [ 7,  1,  1]]], dtype=int32)

In [59]:
x = np.random.randint(1,21, size=(2,2))
y = np.random.randint(1,21, size=(2,2))
print(x)
print(y)

[[13  8]
 [ 2 11]]
[[10 19]
 [10  4]]


In [60]:
print(x+y)   #element multiplication
print(x-y)
print(x*y)

[[23 27]
 [12 15]]
[[  3 -11]
 [ -8   7]]
[[130 152]
 [ 20  44]]


In [61]:
#matrix multiplicatiopn
#1st method
print(x @ y)

[[210 279]
 [130  82]]


In [62]:
#2nd method
np.dot(x,y)

array([[210, 279],
       [130,  82]], dtype=int32)

In [63]:
x.prod()   #prod = product

np.int64(2288)

In [64]:
x.mean()  #mean = avg value

np.float64(8.5)

In [65]:
y.mean()

np.float64(10.75)

In [66]:
b = x.mean(axis=0)   #column wise   axis= 0 ->  column and Axis= 1 -> row
print(b)

[7.5 9.5]


In [67]:
c = x.mean(axis=1) #row wise
print(c)

[10.5  6.5]


In [68]:
x.sum()

np.int64(34)

In [69]:
print(x.sum())   #std = standard deviation
print(x.std())   #var = varience
print(x.var())

34
4.153311931459037
17.25


In [70]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(arr,50))
print(np.percentile(arr,25))
print(np.percentile(arr, 75))


5.0
3.0
7.0


In [71]:
arr2 = np.random.randint(11,100, (4,4))
print('2x8')
print(arr2.reshape(2,8))
print('8x2')
print(arr2.reshape(8,2))

2x8
[[55 96 72 23 41 19 15 69]
 [66 60 29 54 81 56 64 25]]
8x2
[[55 96]
 [72 23]
 [41 19]
 [15 69]
 [66 60]
 [29 54]
 [81 56]
 [64 25]]


In [72]:
print(arr2)

[[55 96 72 23]
 [41 19 15 69]
 [66 60 29 54]
 [81 56 64 25]]


In [73]:
print(arr2[0])  #0th row
print(arr2[0,1])  #oth row 1st column
print(arr2[-1])  #last row
print(arr2[:3])  #0th to 2nd row 
print(arr2[1:])  #1st to last row

[55 96 72 23]
96
[81 56 64 25]
[[55 96 72 23]
 [41 19 15 69]
 [66 60 29 54]]
[[41 19 15 69]
 [66 60 29 54]
 [81 56 64 25]]


In [74]:
arr2 > 50

array([[ True,  True,  True, False],
       [False, False, False,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [81]:
y = arr2[arr2>50]
z = y.reshape(5,2)
print(z)

[[55 96]
 [72 69]
 [66 60]
 [54 81]
 [56 64]]
